{% set name = "coin-or-cbc" %}
{% set version = "2.10.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/coin-or/Cbc/archive/releases/{{ version }}.tar.gz
    sha256: cc44c1950ff4615e7791d7e03ea34318ca001d3cac6dc3f7f5ee392459ce6719

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - make  # [unix]
  host:
    - coin-or-cgl
  run_constrained:
    - coincbc * *_metapackage

test:
  commands:
    - test -f $PREFIX/lib/libCbc${SHLIB_EXT}
    - test -f $PREFIX/include/coin/CbcConfig.h
    - test -f $PREFIX/lib/libCbcSolver${SHLIB_EXT}
    - test -f $PREFIX/lib/libOsiCbc${SHLIB_EXT}
    - echo ? | cbc

about:
  home: https://projects.coin-or.org/Cbc
  dev_url: https://github.com/coin-or/Cbc
  license: EPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: COIN-OR branch and cut (Cbc)
  description: |
    Cbc (Coin-or branch and cut) is an open-source mixed integer linear
    programming solver written in C++. It can be used as a callable library or
    using a stand-alone executable. It can be called through AIMMS (through the
    AIMMSlinks project), AMPL (natively), CMPL, GAMS (through the GAMSlinks
    project), JuMP, Mathematica, MiniZinc, MPL (through the CoinMP project), PuLP,
    Python (e.g., cbcpy), and OpenSolver for Excel, among others.

extra:
  recipe-maintainers:
    - wolfv
    - tkralphs
